### ISSUE TITLE
requires strict mode

### ISSUE THREAD

**Issue by ipc103** [learn-co-curriculum/javascript-fix-this#3]
the tests failed for about half the students in the class unless they were using strict mode. Is this a problem, or should we just add 'use strict' to the test file?

**Comment by aturkewi** [comment]
@ipc103 what tests were failing? All tests?

I feel like I usually see an error like this when students are not using the most recent version of Node as well.

**Comment by ipc103** [comment]
Certainly possible that they had an old version of node - the error was very specific that strict mode was required.

Avidor pointed me to `n` - which we'll start having students use for their setup.

**Comment by drakeltheryuujin** [comment]
Haven't seen this raised as an issue in a couple years, so I'm going to close this for now assuming that it has been resolved.

Thanks! 💙
