### ISSUE TITLE
Solution has unnecessary and misleading argument

### ISSUE THREAD

**Issue by jef4490** [learn-co-curriculum/javascript-fix-this#5]
On lines 28 & 34 of the index.js solution file, the update${item}Status method is passed an unnecessary argument of "Prep". This is a little misleading and not hinted towards or checked in the test files.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
